split code into two stores
dooboolab/react-native-iap pull request #1336
Opened 2021-05-13 22:55 UTC by andresesfm

2021-06-02 16:51 UTC, andresesfm commented on src/iap.ts
> +      return RNIapModule ? RNIapModule.flushFailedPurchasesCachedAsPending() :[];
can be improved later

2021-06-02 16:51 UTC, andresesfm commented on .gitignore
> -*.js
This makes it difficult to search inside IapExample folder since vscode ignores all the js.

2021-06-02 16:51 UTC, andresesfm commented on IapExample/App.js
> -      const result = await RNIap.initConnection();
returns void, no need to log it

2021-06-02 16:51 UTC, andresesfm commented on IapExample/App.js
> +        const receipt =  purchase.transactionReceipt? purchase.transactionReceipt : purchase.originalJson;
receipt is named something different on Amazon and Google

2021-06-02 16:51 UTC, andresesfm commented on IapExample/android/app/build.gradle
> +    flavorDimensions "appstore"
An example where the dimension name in the client app is different from the one in the library

2021-06-02 16:51 UTC, andresesfm commented on IapExample/android/app/build.gradle
> +    implementation project(path: ':react-native-iap')
pointing to local file for quick debug

2021-06-02 16:51 UTC, andresesfm commented on IapExample/android/settings.gradle
> +include ':react-native-iap'
pointing to local for quick debug iteration

2021-06-02 16:51 UTC, andresesfm commented on IapExample/package.json
> +    "react-native-iap": "file:..",
pointing to local for quick debug iteration

2021-06-02 16:51 UTC, andresesfm commented on README.md
> -5. Add the following to the `<permission>` block in `android/app/src/main/AndroidManifest.xml`:
No longer needed as it's part of the new implementation

2021-06-02 16:51 UTC, andresesfm commented on README_AMAZON.md
> -  2. Update AndroidManifest.xml to add the following:
No longer needed, it's part of the library implementation now

2021-06-02 16:51 UTC, andresesfm commented on android/build.gradle
> +  amazonImplementation fileTree(dir: 'libs', include: ['*.jar'])
Splitting libraries per flavor. Reduces the bundle size and avoids bugs like the one we are seeing with OneSignal

2021-06-02 16:51 UTC, andresesfm commented on android/src/amazon/java/com/dooboolab/RNIap/RNIapAmazonModule.java
> +    UiThreadUtil.runOnUiThread(() -> {
This new implementation follows Amazon's documentation guidelines
https://developer.amazon.com/docs/in-app-purchasing/iap-implement-iap.html#4-implement-getpurchaseupdates-method

2021-06-02 16:51 UTC, andresesfm commented on android/src/amazon/java/com/dooboolab/RNIap/RNIapAmazonModule.java
> +    RequestId requestId = PurchasingService.getProductData(productSkus);
Change in order prevents unlikely race condition

2021-06-02 16:51 UTC, andresesfm commented on src/iap.ts
>  async function detectInstallSourceAndroid(): Promise<void> {
The method could be reimplemented in a simplified way, TODO

2021-06-02 16:51 UTC, andresesfm commented on src/iap.ts
> -    const emitterSubscription = DeviceEventEmitter.addListener(
It is now deprecated

2021-06-04 00:41 UTC, andresesfm commented on android/build.gradle
> +  amazonImplementation fileTree(dir: 'libs', include: ['*.jar'])
This crash is resolved with this PR: https://github.com/dooboolab/react-native-iap/issues/1291

2021-06-06 07:02 UTC, hyochan requested changes
Thanks for real hard work @andresesfm. You've rocked the `Amazon` iap.

I've just given small reviews and would like to test my previous android app if things aren't breaking after changes.

Also, since this is pretty much a heavy update, I would prefer you to update the version to `6.1.0` instead of `6.0.10`.

2021-06-09 13:03 UTC, hyochan reviewed
@andresesfm Hi. I think you're done with the review fixes and I've just tried installing this new version in [dooboolab.com pull request](https://github.com/hyochan/dooboolab.com/pull/16) by `yarn add react-native-iap@next` which is currently version `6.1.0`. However, I am facing the below build error. Could you kindly look into this and see what should be done to solve the build problem?

I am afraid if we are missing additional context for the previous user. The above project was using `6.0.3` which did not have a build problem.

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :react-native-iap.
     Required by:
         project :app
      > The consumer was configured to find a runtime of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug'. However we cannot choose between the following variants of project :react-native-iap:
          - amazonDebugRuntimeElements
          - playDebugRuntimeElements
        All of them match the consumer attributes:
          - Variant 'amazonDebugRuntimeElements' capability dooboolab:react-native-iap:unspecified declares a runtime of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug':
              - Unmatched attributes:
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'amazonDebug' but the consumer didn't ask for it
                  - Provides attribute 'store' with value 'amazon' but the consumer didn't ask for it
          - Variant 'playDebugRuntimeElements' capability dooboolab:react-native-iap:unspecified declares a runtime of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug':
              - Unmatched attributes:
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'playDebug' but the consumer didn't ask for it
                  - Provides attribute 'store' with value 'play' but the consumer didn't ask for it
        The following variants were also considered but didn't match the requested attributes:
          - Variant 'amazonDebugApiElements' capability dooboolab:react-native-iap:unspecified declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug':
              - Incompatible because this component declares an API of a component and the consumer needed a runtime of a component
          - Variant 'amazonReleaseApiElements' capability dooboolab:react-native-iap:unspecified:
              - Incompatible because this component declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release' and the consumer needed a runtime of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug'
          - Variant 'amazonReleaseRuntimeElements' capability dooboolab:react-native-iap:unspecified declares a runtime of a component:
              - Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release' and the consumer needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug'
          - Variant 'playDebugApiElements' capability dooboolab:react-native-iap:unspecified declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug':
              - Incompatible because this component declares an API of a component and the consumer needed a runtime of a component
          - Variant 'playReleaseApiElements' capability dooboolab:react-native-iap:unspecified:
              - Incompatible because this component declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release' and the consumer needed a runtime of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug'
          - Variant 'playReleaseRuntimeElements' capability dooboolab:react-native-iap:unspecified declares a runtime of a component:
              - Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release' and the consumer needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.
```

2021-06-09 13:09 UTC, hyochan approved these changes
I've just find out the solution in the `README.md`.

```
missingDimensionStrategy 'store', 'play'
```

Thanks a lot for your contribution :pray: 
I also like to reward you for this `PR`. 

Could you submit expense in [react-native-iap opencollective](https://opencollective.com/react-native-iap)? I want to reward you with $50. know it isn't much but I want to thank you for helping react-native-iap.

2021-06-09 13:10 UTC, merged