Master
dooboolab/react-native-iap pull request #1742
Opened 2022-07-08 11:07 UTC by nguyendinhnhan

2022-07-09 06:31 UTC, hyochan requested changes
@nguyendinhnhan Thanks so much for your work.

Could you kindly check the CI failing from the kotlin linter and request a review?

Also, I wish you can try to give more information on the title and the description.

2022-07-09 21:10 UTC, andresesfm commented on android/src/amazon/java/com/dooboolab/RNIap/RNIapAmazonListener.kt
> +                            Currency.getInstance("VND")
Should this be a parameter? Or maybe it can be obtained from the payload? This makes it very specific to your locale

2022-07-09 21:10 UTC, andresesfm commented on android/src/amazon/java/com/dooboolab/RNIap/RNIapAmazonListener.kt
> +// Begin Add localizedPrice12
Linter complains about the order of these imports

2022-07-09 21:10 UTC, andresesfm commented on package.json
> +  "main": "index.ts",
This is only an issue when testing locally. For the release, this needs to be reverted to js

2022-07-09 21:10 UTC, andresesfm commented on src/types/index.ts
> +  localizedPrice12: string;
What's the meaning of the '12'?

2022-07-17 23:37 UTC, andresesfm commented
Sorry but this doesn't seem generic-enough to be included in this library

2022-07-17 23:37 UTC, closed without merging